### ISSUE TITLE
[Library] Import fetch API polyfill

### ISSUE THREAD

**Issue by rickychien** [ShiningGeneration/majaja#13]
Majaja uses lots of super new Web API - fetch, it doesn't support yet on safari and IE. Thus, we're able to import fetch's polyfill to workaround it.

See also https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Browser_compatibility

**Comment by dwi2** [comment]
May I try this?

**Comment by rickychien** [comment]
Sure!

**Comment by dwi2** [comment]
Here's the [`fetch` shim](https://github.com/github/fetch)
and here's [how to use webpack with it](http://mts.io/2015/04/08/webpack-shims-polyfills/)
