### ISSUE TITLE
[CreateStore] Upload product image

### ISSUE THREAD

**Issue by rickychien** [ShiningGeneration/majaja#16]
We should have a multiple files uploader to upload images.

**Comment by john-hu** [comment]
@rickychien WTF, why am I not in the group??

**Comment by rickychien** [comment]
Invitation sent.

**Comment by rickychien** [comment]
@john-hu Please accept the invitation (from email) to join this group.

**Comment by john-hu** [comment]
Ha.. I accept it.

**Comment by john-hu** [comment]
Let me try to modify it.
