### ISSUE TITLE
[Order] Complete number / amount picker

### ISSUE THREAD

**Issue by rickychien** [ShiningGeneration/majaja#7]
Current picker doesn't work. Order view should have a workable number / amount picker.

**Comment by rickychien** [comment]
@KuoE0 I think you're the best full stack engineer in the world and have enough knowledge to complete the task.

**Comment by dwi2** [comment]
Totally agree with @rickychien.
@KuoE0 is the best! :+1: 
[![LGTM](http://lgtm.in/p/CbqeKakFn)](http://lgtm.in/i/CbqeKakFn)
